version: '3.8'

services:
  # 1. SERVICE: DATABASE (MongoDB)
  mongo:
    image: mongo:6
    container_name: my-mongo
    ports:
      - '27017:27017' # Cho phép máy ngoài (ví dụ Compass) kết nối vào xem DB
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db # Lưu dữ liệu ra ổ cứng thật để không mất khi tắt container
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. SERVICE: APP (NestJS)
  api:
    build: . # Build từ Dockerfile ở thư mục hiện tại
    container_name: my-server
    ports:
      - '8080:8080' # Map cổng ra ngoài
    depends_on:
      mongo:
        condition: service_healthy # Chờ MongoDB ở trạng thái Healthy rồi mới chạy App
    env_file:
      - .env # Đọc các biến môi trường khác
    environment:
      # GHI ĐÈ biến MONGODB_URI để trỏ vào service 'mongo' bên trên
      # "mongo" ở đây chính là tên service (hostname) trong mạng nội bộ Docker
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/my_database_name?authSource=admin

    # [DEV MODE] Cấu hình để sửa code là server tự cập nhật (Hot Reload)
    volumes:
      - .:/app # "Đục lỗ" nối thư mục code máy bạn vào trong container
      - /app/node_modules # Giữ riêng thư viện của container (tránh xung đột với máy thật)
    command: npm run start:dev # Chạy lệnh dev thay vì lệnh prod mặc định

volumes:
  mongo_data: # Khai báo volume để lưu dữ liệu bền vững
